### ISSUE TITLE
thought list should display in reverse order

### ISSUE THREAD

**Issue by danfaeh** [Jehnean/hmwk-microblog#3]
instead of using append, consider using the prepend method. So the newest person to leave their thought can see it at the top of the list.

**Comment by Jehnean** [comment]
Excellent recommendation. 

Swapped .append method with .prepend method. 
<img width="1052" alt="screen shot 2016-01-31 at 8 51 10 pm" src="https://cloud.githubusercontent.com/assets/6146792/12709041/7c8b9902-c85c-11e5-87f3-f2b61f011a15.png">
<img width="615" alt="screen shot 2016-01-31 at 8 52 17 pm" src="https://cloud.githubusercontent.com/assets/6146792/12709046/8bf1c4b6-c85c-11e5-864a-fba221d1941c.png">
